management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: "*"
spring:
  main:
    banner-mode: off
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  datasource:
    url: jdbc:h2:mem:db;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: sa
    platform: h2
logging:
  level:
    org.springframework.cloud: debug
    nc.unc.cs.services: debug
    com:
      netflix:
        eureka: OFF
        discovery: OFF
    org:
      springframework:
        web:
          client:
            RestTemplate: OFF
zuul:
  host:
    connect-timeout-millis: 60000
    socket-timeout-millis: 60000
  routes:
    account:
      path: /auth/**
      service-id: ACCOUNT
      strip-prefix: true
      sensitive-headers: '*'
      url: ${config.protocol}://${ACCOUNT_URL:localhost:8888}/auth
    bank:
      path: /bank/**
      service-id: BANK
      strip-prefix: true
      sensitive-headers: '*'
      url:  ${config.protocol}://${BANK_URL:localhost:8084}/bank
    communal:
      path: /communal/**
      service-id: COMMUNAL
      strip-prefix: true
      sensitive-headers: '*'
      url: ${config.protocol}://${COMMUNAL_URL:localhost:8083}/communal
    passport:
      path: /passport/**
      service-id: PASSPORT
      strip-prefix: true
      sensitive-headers: '*'
      url: ${config.protocol}://${PASSPORT_URL:localhost:8095}/passport
    tax:
      path: /passport/**
      service-id: TAX
      strip-prefix: true
      sensitive-headers: '*'
      url: ${config.protocol}://${TAX_URL:localhost:8082}/tax
    gibdd:
      path: /gibdd/**
      service-id: GIBDD
      strip-prefix: true
      sensitive-headers: '*'
      url: ${config.protocol}://${GIBDD_URL:localhost:8088}/gibdd
    logger:
      path: /logger/**
      service-id: LOGGER
      strip-prefix: true
      sensitive-headers: '*'
      url: ${config.protocol}://${LOGGING_URL:localhost:8089}/logs