version = 1

test_patterns = [
  "test/**",
  "**/test/**/*.java"
]

exclude_patterns = [
  "*.pom",
  "**/*.pom",
  "*.js",
  "**/*.js",
  "*.xml",
  "**/*.xml"
]

[[analyzers]]
name = "java"
enabled = true

[analyzers.meta]
runtime_version = "8"

[[transformers]]
name = "prettier"
enabled = false
