---
enabled: true
auto: false
exclude:
  - "**/*.patch"
  - "**/node_modules/**/*"
  - "**/vendor/**/*"
  - ".github/workflows/**/*"
  - "**/target/**"
  - ".github/*"
  - "homework/*"
commit_template: Restyled by ${restyler.name}
pull_requests: true
comments: false
statuses:
  differences: true # Red when style differences are found
  no_differences: true # Green when no differences are found
  error: true # Red if we encounter errors restyling
request_review: author
restylers_version: stable
restylers:
  - "clang-format"
  - "google-java-format"
  - "prettier-json"
  - "prettier-markdown"
  - "prettier-yaml"
