version: "3.9"
services:
  discovery:
    restart: always
    build:
      context: .
      args:
        JAR_FILE: discovery/target/discovery-0.0.1-SNAPSHOT.jar
    container_name: discovery
    deploy:
      resources:
        limits:
          cpus: 0.50
          memory: 200M
        reservations:
          memory: 200M
    environment:
      - APP_XMX=200m
      - APP_XMS=200m
      - APP_URL=discovery:8080
    ports:
      - "8761:8080"
  config:
    restart: always
    build:
      context: .
      args:
        JAR_FILE: config/target/config-0.0.1-SNAPSHOT.jar
    container_name: config
    depends_on:
      - discovery
    deploy:
      resources:
        limits:
          cpus: 0.50
          memory: 150M
        reservations:
          memory: 85M
    environment:
      - APP_XMX=150m
      - APP_XMS=85m
      - EUREKA_HOST=discovery:8080
      - APP_URL=config:8080
      - SPRING_PROFILES_ACTIVE=native
    ports:
      - "8762:8080"
  logging:
    restart: always
    build:
      context: .
      args:
        JAR_FILE: services/logging/target/logging-0.0.1-SNAPSHOT.jar
    container_name: logging
    depends_on:
      - discovery
      - config
    deploy:
      resources:
        limits:
          cpus: 0.50
          memory: 300M
        reservations:
          memory: 100M
    environment:
      - APP_XMX=300M
      - APP_XMS=100M
      - EUREKA_HOST=discovery:8080
      - CFG_HOST=config:8080
      - APP_URL=logging:8080
    ports:
      - "8089:8080"
  tax:
    restart: always
    build:
      context: .
      args:
        JAR_FILE: services/tax/target/tax-0.0.1-SNAPSHOT.jar
    container_name: tax
    depends_on:
      - discovery
      - config
      - logging
    deploy:
      resources:
        limits:
          cpus: 0.50
          memory: 300M
        reservations:
          memory: 100M
    environment:
      - APP_XMX=300M
      - APP_XMS=100M
      - EUREKA_HOST=discovery:8080
      - CFG_HOST=config:8080
      - LOGGING_URL=logging:8080
      - APP_URL=tax:8080
    ports:
      - "8094:8080"
  gibdd:
    restart: always
    build:
      context: .
      args:
        JAR_FILE: services/gibdd/target/gibdd-0.0.1-SNAPSHOT.jar
    container_name: gibdd
    depends_on:
      - discovery
      - config
      - logging
    deploy:
      resources:
        limits:
          cpus: 0.50
          memory: 300M
        reservations:
          memory: 100M
    environment:
      - APP_XMX=300M
      - APP_XMS=100M
      - EUREKA_HOST=discovery:8080
      - CFG_HOST=config:8080
      - LOGGING_URL=logging:8080
      - APP_URL=gibdd:8080
    ports:
      - "8088:8080"
  account:
    restart: always
    build:
      context: .
      args:
        JAR_FILE: services/account/target/account-0.0.1-SNAPSHOT.jar
    container_name: account
    depends_on:
      - discovery
      - config
    deploy:
      resources:
        limits:
          cpus: 0.50
          memory: 300M
        reservations:
          memory: 100M
    environment:
      - APP_XMX=300M
      - APP_XMS=100M
      - EUREKA_HOST=discovery:8080
      - CFG_HOST=config:8080
      - LOGGING_URL=logging:8080
      - APP_URL=account:8080
    ports:
      - "8090:8080"
  bank:
    restart: always
    build:
      context: .
      args:
        JAR_FILE: services/bank/target/bank-0.0.1-SNAPSHOT.jar
    container_name: bank
    depends_on:
      - discovery
      - config
      - logging
      - tax
    deploy:
      resources:
        limits:
          cpus: 0.50
          memory: 300M
        reservations:
          memory: 100M
    environment:
      - APP_XMX=300M
      - APP_XMS=100M
      - EUREKA_HOST=discovery:8080
      - CFG_HOST=config:8080
      - LOGGING_URL=logging:8080
      - APP_URL=bank:8080
    ports:
      - "8091:8080"
  communal:
    restart: always
    build:
      context: .
      args:
        JAR_FILE: services/communal/target/communal-0.0.1-SNAPSHOT.jar
    container_name: communal
    depends_on:
      - discovery
      - config
      - logging
      - bank
      - tax
    deploy:
      resources:
        limits:
          cpus: 0.50
          memory: 300M
        reservations:
          memory: 100M
    environment:
      - APP_XMX=300M
      - APP_XMS=100M
      - EUREKA_HOST=discovery:8080
      - CFG_HOST=config:8080
      - LOGGING_URL=logging:8080
      - APP_URL=communal:8080
    ports:
      - "8092:8080"
  passport:
    restart: always
    build:
      context: .
      args:
        JAR_FILE: services/passport/target/passport-0.0.1-SNAPSHOT.jar
    container_name: passport
    depends_on:
      - discovery
      - config
      - logging
      - bank
      - tax
    deploy:
      resources:
        limits:
          cpus: 0.50
          memory: 300M
        reservations:
          memory: 100M
    environment:
      - APP_XMX=300M
      - APP_XMS=100M
      - EUREKA_HOST=discovery:8080
      - CFG_HOST=config:8080
      - LOGGING_URL=logging:8080
      - APP_URL=passport:8080
    ports:
      - "8093:8080"
  frontend:
    restart: always
    build:
      context: client-ui
    container_name: frontend
    depends_on:
      - discovery
      - config
    deploy:
      resources:
        limits:
          cpus: 0.50
          memory: 300M
        reservations:
          memory: 100M
    ports:
      - "3000:8080"
