version: 2.1

orbs:
  maven: circleci/maven@1.1
  docker: circleci/docker@1.5.0
  heroku: circleci/heroku@1.2.6

jobs:
  build-and-push:
    executor:
      name: docker/machine
      dlc: true
    steps:
      - setup_remote_docker:
          version: 19.03.13
          docker_layer_caching: true
      - checkout
      - create_concatenated_checksum_file:
          filename: poms.lock
      - heroku/install
      - heroku/check-authentication
      # build and push Docker image
      - run: |
          chmod +x .circleci/build_baseline_images.sh
          chmod +x .circleci/build_service_images.sh
      - run: |
          BRANCH_NAME=${CIRCLE_BRANCH}
      - run: |
          .circleci/build_baseline_images.sh
      - run: |
          .circleci/build_service_images.sh
workflows:
  maven_test:
    jobs:
      - maven/test
  docker_build:
    jobs:
      - build-and-push

