version: 2.1

orbs:
  maven: circleci/maven@1.1
  docker: circleci/docker@1.5.0
  heroku: circleci/heroku@1.2.6

jobs:
  build-and-push:
    executor: docker/docker
    steps:
      - setup_remote_docker:
          version: 19.03.13
          docker_layer_caching: true
      - checkout
      - heroku/install
      - heroku/check-authentication
      # build and push Docker image
      - run: |
          chmod +x .circleci/build_docker_images.sh
      - run: |
          heroku login
          heroku container:login
      - run: |
          echo $DOCKER_PASSWORD | docker login -u $DOCKER_LOGIN --password-stdin
      - run: |
          BRANCH_NAME=${CIRCLE_BRANCH}
      - run: |
          .circleci/build_docker_images.sh
workflows:
  maven_test:
    jobs:
      - maven/test
  docker_build:
    jobs:
      - build-and-push

