version: 2.1

orbs:
  maven: circleci/maven@1.1
  docker: circleci/docker@1.5.0

jobs:
  build-and-push:
    executor: docker/docker
    steps:
      - setup_remote_docker:
          version: 19.03.13
          docker_layer_caching: true
      - checkout
      # build and push Docker image
      - run: |
          echo $DOCKER_PASSWORD | docker login -u $DOCKER_LOGIN --password-stdin
          TAG=circle_ci.$CIRCLE_BUILD_NUM
          docker build -f baseline.back.Dockerfile -t kostua16/unc_2020_backend_base:circle_ci .
          docker build -f baseline.frontend.Dockerfile -t kostua16/unc_2020_frontend_base:circle_ci .
          docker tag  kostua16/unc_2020_backend_base:circle_ci kostua16/unc_2020_backend_base:$TAG
          docker tag  kostua16/unc_2020_frontend_base:circle_ci kostua16/unc_2020_frontend_base:$TAG
          docker push kostua16/unc_2020_backend_base:circle_ci
          docker push kostua16/unc_2020_frontend_base:circle_ci
          docker push kostua16/unc_2020_backend_base:$TAG
          docker push kostua16/unc_2020_frontend_base:$TAG
workflows:
  maven_test:
    jobs:
      - maven/test
  docker_build:
    jobs:
      - build-and-push

