version: 2.1

orbs:
  maven: circleci/maven@1.1
  docker: circleci/docker@1.5.0
  heroku: circleci/heroku@1.2.6
commands:
  create_concatenated_checksum_file:
    description: "Concatenate checksums from all pom.xml files into single file. File is used as checksum source for part of caching key."
    parameters:
      filename:
        type: string
    steps:
      - run:
          name: Combine package-lock.json files to single file
          command: find ./ -type f  -name pom.xml | xargs cat > << parameters.filename >>
jobs:
  build-baseline-images:
    executor:
      name: docker/machine
      dlc: true
    steps:
      - checkout
      - heroku/install
      - heroku/check-authentication
      - run: |
          chmod +x .circleci/build_backend_baseline_image.sh
          chmod +x .circleci/build_frontend_baseline_image.sh
      - run: |
          BRANCH_NAME=${CIRCLE_BRANCH}
      - run: |
          if ["$BRANCH_NAME" == "develop"]; then
            time .circleci/build_backend_baseline_image.sh
          fi
      - run: |
          if ["$BRANCH_NAME" == "develop"]; then
            time .circleci/build_frontend_baseline_image.sh
          fi
  build-backend-service:
    executor:
      name: docker/machine
      dlc: true
    parameters:
      service_name:
        description: The name of the service
        type: string
        default: discovery
      target_app:
        description: The name of the target heroku app to deploy
        type: string
        default: nc-edu-2020-discovery
    steps:
      - checkout
      - heroku/install
      - heroku/check-authentication
      - run: |
          chmod +x .circleci/build_backend_service.sh
      - run: |
          BRANCH_NAME=${CIRCLE_BRANCH}
      - run: |
          .circleci/build_backend_service.sh << parameters.service_name >> << parameters.target_app >>
  build-frontend-service:
    executor:
      name: docker/machine
      dlc: true
    steps:
      - checkout
      - heroku/install
      - heroku/check-authentication
      - run: |
          chmod +x .circleci/build_frontend_service.sh
      - run: |
          BRANCH_NAME=${CIRCLE_BRANCH}
      - run: |
          .circleci/build_frontend_service.sh
workflows:
  maven_test:
    jobs:
      - maven/test
  docker_build:
    jobs:
      - build-baseline-images
      - build-backend-service:
          name: build-discovery
          service_name: discovery
          target_app: nc-edu-2020-discovery
          requires:
            - build-baseline-images
      - build-backend-service:
          name: build-config
          service_name: config
          target_app: nc-edu-2020-config
          requires:
            - build-baseline-images
      - build-backend-service:
          name: build-proxy
          service_name: proxy
          target_app: nc-edu-2020-proxy
          requires:
            - build-baseline-images
      - build-backend-service:
          name: build-logging
          service_name: logging
          target_app: nc-edu-2020-logger
          requires:
            - build-baseline-images
            - build-discovery
            - build-config
      - build-backend-service:
          name: build-tax
          service_name: tax
          target_app: nc-edu-2020-tax
          requires:
            - build-baseline-images
            - build-discovery
            - build-config
      - build-backend-service:
          name: build-gibdd
          service_name: gibdd
          target_app: nc-edu-2020-gibdd
          requires:
            - build-baseline-images
            - build-discovery
            - build-config
      - build-backend-service:
          name: build-account
          service_name: account
          target_app: nc-edu-2020-account
          requires:
            - build-baseline-images
            - build-discovery
            - build-config
      - build-backend-service:
          name: build-bank
          service_name: bank
          target_app: nc-edu-2020-bank
          requires:
            - build-baseline-images
            - build-discovery
            - build-config
      - build-backend-service:
          name: build-communal
          service_name: communal
          target_app: nc-edu-2020-communal
          requires:
            - build-baseline-images
            - build-discovery
            - build-config
      - build-backend-service:
          name: build-passport
          service_name: passport
          target_app: nc-edu-2020-passport
          requires:
            - build-baseline-images
            - build-discovery
            - build-config
      - build-frontend-service:
          name: build-frontend
          requires:
            - build-baseline-images
            - build-discovery
