version: 2.1

orbs:
  maven: circleci/maven@1.1
  docker: circleci/docker@1.5.0
  heroku: circleci/heroku@1.2.6
commands:
  create_concatenated_checksum_file:
    description: "Concatenate checksums from all pom.xml files into single file. File is used as checksum source for part of caching key."
    parameters:
      filename:
        type: string
    steps:
      - run:
          name: Combine package-lock.json files to single file
          command: find ./ -type f  -name pom.xml | xargs cat > << parameters.filename >>
jobs:
  build-and-push:
    executor:
      name: docker/machine
      dlc: true
    steps:
#      - setup_remote_docker:
#          version: 19.03.13
#          docker_layer_caching: true
      - checkout
      - create_concatenated_checksum_file:
          filename: poms.lock
      - heroku/install
      - heroku/check-authentication
      # build and push Docker image
      - run: |
          chmod +x .circleci/build_backend_baseline_image.sh
          chmod +x .circleci/build_frontend_baseline_image.sh
          chmod +x .circleci/build_backend_service.sh
          chmod +x .circleci/build_frontend_service.sh
      - run: |
          BRANCH_NAME=${CIRCLE_BRANCH}
      - run: |
          if ["$BRANCH_NAME" == "develop"]; then
            time .circleci/build_backend_baseline_image.sh
          fi
      - run: |
          if ["$BRANCH_NAME" == "develop"]; then
            time .circleci/build_frontend_baseline_image.sh
          fi
      - run: |
          .circleci/build_backend_service.sh discovery nc-edu-2020-discovery
      - run: |
          .circleci/build_backend_service.sh config nc-edu-2020-config
      - run: |
          .circleci/build_backend_service.sh proxy nc-edu-2020-proxy
      - run: |
          .circleci/build_backend_service.sh logging nc-edu-2020-logger
      - run: |
          .circleci/build_backend_service.sh tax nc-edu-2020-tax
      - run: |
          .circleci/build_backend_service.sh gibdd nc-edu-2020-gibdd
      - run: |
          .circleci/build_backend_service.sh account nc-edu-2020-account
      - run: |
          .circleci/build_backend_service.sh bank nc-edu-2020-bank
      - run: |
          .circleci/build_backend_service.sh communal nc-edu-2020-communal
      - run: |
          .circleci/build_backend_service.sh passport nc-edu-2020-passport
      - run: |
          .circleci/build_frontend_service.sh
workflows:
  maven_test:
    jobs:
      - maven/test
  docker_build:
    jobs:
      - build-and-push

