management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: "*"
spring:
  main:
    banner-mode: off
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  datasource:
    url: jdbc:h2:mem:db;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: sa
    platform: h2
logging:
  level:
    org.springframework.cloud: debug
    nc.unc.cs.services: debug
    com:
      netflix:
        eureka: OFF
        discovery: OFF
    org:
      springframework:
        web:
          client:
            RestTemplate: OFF
communal:
  background:
    job:
      tax-period: 1
      timeout: 60000
      property-tax:
        period: ${PROPERTY_TAX_CHECK_PERIOD:20000}
        page-size: ${PROPERTY_TAX_CHECK_SIZE:10}
      utility-bill:
        period: ${UTILITY_BILL_CHECK_PERIOD:20000}
        page-size: ${UTILITY_BILL_CHECK_SIZE:10}
  property:
    tax-percent: 10
  service-id:
    property-tax: 20