management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: "*"
spring:
  main:
    banner-mode: off
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  datasource:
    url: jdbc:h2:mem:db;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: sa
    platform: h2
logging:
  pattern:
    console: "%d %-5level %logger : %msg%n"
    file: "%d %-5level [%thread] %logger : %msg%n"
  level:
    root: WARN
    nc.unc.cs.services: TRACE
    com.netflix.eureka: ERROR
    com.netflix.discovery: ERROR
    org.springframework: WARN
    org.springframework.cloud: INFO
    org.springframework.web.client.RestTemplate: WARN
server:
  tomcat:
    threads:
      max: 10
      min-spare: 3
  jetty:
    threads:
      max: 10
      min: 3

