name: "Labeler"
on:
  - pull_request_target

jobs:
  triage:
    name: Set labels
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@main
        with:
          sync-labels: true
          repo-token: "${{ secrets.GH_TKN }}"
