---
###########################
###########################
## Linter GitHub Actions ##
###########################
###########################
name: Build project with Maven On Demand

#
# Documentation:
# https://help.github.com/en/articles/workflow-syntax-for-github-actions
#

#############################
# Start the job on PR comment #
#############################
on:
  issue_comment:
    types: [created]

###############
# Set the Job #
###############
jobs:
  on_demand_lint:
    # Name the Job
    name: Build project with Maven On Demand
    # Set the agent to run on
    runs-on: ubuntu-latest
    if: contains(github.event.comment.body, '/build')
    ##################
    # Load all steps #
    ##################
    steps:
      ##########################
      # Checkout the code base #
      ##########################
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          # Full git history is needed to get a proper list of changed files within `super-linter`
          fetch-depth: 0

      ################################
      # Cache local Maven repository #
      ################################
      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      ##############
      # Setup JAVA #
      ##############
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      ########################
      # Try to build project #
      ########################
      - name: Build with Maven
        run: mvn -T 2C -B package --file pom.xml

      ##############################
      # Run Junit report generator #
      ##############################
      - name: Run Junit report generator
        uses: check-run-reporter/action@v2.0.0
        if: ${{ always() }}
        with:
          # This label is more complex than you probably want. Since we're
          # running this workflow for both push and pull_request events to test
          # the action itself, we're effectively running the workflwo twice for
          # each PR Commit and we need to differentiate in the UI.
          label: 'Unit Tests (${{ github.event_name }})'
          report: '**/surefire-reports/*.xml'
          token: ${{ secrets.CHECK_RUN_REPORTER_TOKEN }}
